config/routes.rb
Rails.application.routes.draw do

  root 'customers/homes#top'

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    get 'homes/top'
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  namespace :customers do
    get 'homes/about'
    post 'orders/confirm'
    get 'orders/complete'
    resources :orders, only:[:new, :create, :index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :items, only:[:index, :show]
    get 'customers/my_page/:id' => 'customers#show', as: 'my_page'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
    resources :customers, only:[:edit, :update]
    delete 'cart_items/destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :create]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

   belongs_to :customer
   
   validates :name, presence: true
   validates :postal_code, presence: true, length: { is: 7 }
   validates :address, presence: true
 
#  order/newで使う値を定義
   def post_address_name
    '〒' + self.postal_code.tr('０-９', '0-9') + ' ' + self.address + ' '+ self.name
   end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item

    validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :encrypted_password, presence: true,
                                 length: { minimum:8 }

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  #  order/newで使う値を定義
   def full_name
    self.last_name + ' '+ self.first_name
   end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  
  enum is_active: { "販売中": true, "売切れ": false}

  attachment :image

	validates :image, presence: true
  validates :name, presence: true
	validates :introduction, presence: true
	# validates :genre_id, presence: true# ジャンルエラーが2つ出るからこのコードは一旦コメントアウト。
  validates :price, presence: true,  numericality: { only_integer: true } #「numericality: { only_integer: true }」全角入力禁止。
	validates :is_active, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details
  belongs_to :customer
  
  enum payment_method: {"クレジットカード" =>0, "銀行振込" =>1}
    # enum payment_method: {クレジットカード: 0, 銀行振込: 1}
  enum status: {"入金待ち" =>0, "入金確認" =>1, "製作中" =>2, "発送準備中" =>3, "発送済み" =>4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    belongs_to :order
    belongs_to :item
    
    enum making_status: {"製作不可" =>0, "製作待ち" =>1, "製作中" =>2, "製作完了" =>3}
    # enum making_status: {製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  
  before_action :authenticate_admin!
  
  def top
    @today_orders = Order.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  
  before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item), notice: "商品が新しく登録されました。"
    else
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
    item_including_tax = @item.price * 1.1
    @item_including_tax = item_including_tax.floor
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path(@item)
    else
      render 'edit'
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    # 下記の意味：遷移元で与えたパラメータを使って条件分岐
    if params[:order_sort] == "0"
      # 下記の意味：マイページから遷移してきたときはログアウトさせてからパスワード再設定ページに飛ばす
      sign_out
      new_customer_password_path
    elsif current_admin
      admins_homes_top_path
    elsif current_customer.is_deleted == true
      sign_out
      root_path
    elsif customer_signed_in?
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  def index
    @genres = Genre.all
    # 以下ジャンル検索実装の記述箇所
    i = @genres.count #範囲オブジェクトの上限値として使うためにジャンルの個数をiと定義
    n = params[:order_sort].to_i # order_sortで受け取ったパラメータの値を整数型で取得しnと定義する
    case n
    when 1..i #order_sortが1~iの時
      @genre_name = Genre.find(n).name #ジャンルのn番目の主キーのnameカラムを取り出している
      @item_count = Item.where(genre_id: n) #genre_id: 1のカラムを持つ商品全てを配列で取得
      @items_paginate = @item_count.page(params[:page]).per(8) #whereで取り出したデータにページネーションを適用
    else #order_sortがnilの時
      @genre_name = "商品"
      @item_count = Item.all
      @items_paginate = Item.page(params[:page]).per(8)
    end
  end

  def show
    @genres = Genre.all
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_details_helper.rb
module Admins::OrderDetailsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def syouhizei(n)
    # 小数点以下の四捨五入に対応するためにroundを記述
    (n * 1.1).floor.to_s(:delimited)
  end

end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/views/admins/items/edit.html.erb
<div class="container">
  <div class="row">
      <div class="mb-2 offset-md-1">
         <h3 class="admins-items-title">商品編集</h3>
      </div>
  </div>

    <%= form_with model: @item, url: admins_item_path, local: true do |f| %>

        <% if @item.errors.any? %>
    		<div id="error_explanation">
    			<ul>
    				<% @item.errors.full_messages.each do |message| %>
    				<li><%= message %></li>
    				<% end %>
    			</ul>
    		</div>
    	<% end %>

    	<div class="items-form-area">
            <div class="image-area">
                <div>
                    <%= attachment_image_tag @item, :image, fallback: "no_image_square.jpg", id: "img_prev", style: "height: 200px; width:200px;" %><br>
                    <%= f.attachment_field :image %>
                </div>
                
                <script>
                $(document).on("turbolinks:load", function(){
                  function readURL(input) {
                    if(input.files && input.files[0]){
                      var reader = new FileReader();
                      reader.onload = function (e) {
                        $('#img_prev').attr('src', e.target.result);
                      }
                      reader.readAsDataURL(input.files[0]);
                    }
                  }
                  $("#item_image").change(function(){
                    readURL(this);
                  });
                });
                </script>
                
            </div>
            <div class="text-area">
                <table>

                    <tr>
                        <div class="">
                            <th><%= f.label :商品名, class: "" %></th>
                            <td><%= f.text_field :name %></td>
                        </div>
                    </tr>

                    <tr>
                        <div class="">
                            <th><%= f.label :商品説明, class: "" %></th>
                            <td><%= f.text_area :introduction %></td>
                        </div>
                    </tr>

                    <tr>
                        <div class="">
                            <th><%= f.label :ジャンル, class: "" %></th>
                            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択して下さい--" %></td>
                        </div>
                    </tr>

                    <tr>
                        <div class="">
                            <th><%= f.label :税抜き価格, class: "" %></th>
                            <td><%= f.text_field :price %>円</td>
                        </div>
                    </tr>

                    <tr>
                        <div class="">
                            <th><%= f.label :販売ステータス, class: "" %></th>
                            <td><%= f.select :is_active, [["販売中", "販売中"], ["売切れ","売切れ"]], include_blank: "--選択して下さい--" %></td>
                        </div>
                    </tr>
                </table>
            </div>
        </div>

        <div class="text-area-btn">
            <%= f.submit :変更を保存, class: "btn btn-primary" %>
        </div>

    <% end %>

</div>

app/views/admins/items/index.html.erb
<!--<div class="container">-->
  <div class="row">
    <div class="ml-5">
      <h3 class="admins-items-title">商品一覧</h3>
    </div>
  </div>
  
  <div class="rounded-circle-box", style="width:3rem;height:3rem;">
   <%= link_to new_admins_item_path do %>
      <button type="button" class="btn btn-light rounded-circle p-0" style="width:3rem;height:3rem;">
        +
      </button>
    <% end %>
  </div>
  
  <div class="col-12 ">

      <div class="items-index-table mx-auto">
        <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th>商品ID</th>
                    <th>商品画像</th>
                    <th>商品名</th>
                    <th>税抜価格</th>
                    <th>ジャンル</th>
                    <th>ステータス</th>
                </tr>
            </thead>
            <tbody>
                <% @items.each do |item| %>
                <tr>
                    <td width=100><%= item.id %></td>
                    <td width=100><%= attachment_image_tag item, :image, size: '50x50', fallback: 'no_image_square.jpg', size: '50x50' %></td>
                    <td><%= link_to item.name, admins_item_path(item) %></td>
                    <td><%= item.price.to_s(:delimited) %></td>
                    <td><%= item.genre.name %></td>
                    <td><%= item.is_active %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
      </div>
      <div class="offset-md-5 ">
        <%= paginate @items, class: "" %>
      </div>
   </div>
<!--</div>-->

app/views/admins/items/new.html.erb
<div class="container">
  <div class="row">
      <div class="mb-2 offset-md-1">
         <h3 class="admins-items-title">商品新規登録</h3>
      </div>
  </div>

　　<!--下記コメントアウトは保険のコード-->
    <%#= form_with model: @item, url: admins_items_path, scope: :post, local: true do |f| %>

    <%= form_with model: @item, url: admins_items_path, local: true do |f| %>

        <% if @item.errors.any? %>
    		<div id="error_explanation">
    			<ul>
    				<% @item.errors.full_messages.each do |message| %>
    				<li><%= message %></li>
    				<% end %>
    			</ul>
    		</div>
    	<% end %>

    	<div class="items-form-area">

        	    <div class="image-area">
                    <div class="">
                        <div>
                            <%= attachment_image_tag @item, :image, fallback: "no_image_square.jpg", id: "img_prev", style: "height: 200px; width:200px;" %><br>
                            <%= f.attachment_field :image %>
                        </div>
                        
                        <script>
                            $(document).on("turbolinks:load", function(){
                              function readURL(input) {
                                if(input.files && input.files[0]){
                                  var reader = new FileReader();
                                  reader.onload = function (e) {
                                    $('#img_prev').attr('src', e.target.result);
                                  }
                                  reader.readAsDataURL(input.files[0]);
                                }
                              }
                              $("#item_image").change(function(){
                                readURL(this);
                              });
                            });
                        </script>   
                        
                    </div>
                </div>

                <div class="text-area">
                    <table>
                        <tr class="">
                            <div>
                                <th><%= f.label :商品名, class: "" %></th>
                                <td class=""><%= f.text_field :name %></td>
                            </div>
                        </tr>

                        <tr>
                            <div class="">
                                <th><%= f.label :商品説明, class: "" %></th>
                                <td class=""><%= f.text_area :introduction %></td>
                            </div>
                        </tr>

                        <tr>
                            <div class="">
                                <th><%= f.label :ジャンル, class: "" %></th>
                                <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択して下さい--"  %></td>
                            </div>
                        </tr>

                        <tr>
                            <div class="">
                                <th><%= f.label :税抜価格, class: "" %></th>
                                <td><span><%= f.text_field :price %> 円 </span></td>
                            </div>
                        </tr>

                        <tr>
                            <div class="">
                                <th><%= f.label :販売ステータス, class: "" %></th>
                                <td><%= f.select :is_active, [["販売中", "販売中"], ["売切れ","売切れ"]], include_blank: "--選択して下さい--" %></td>
                            </div>
                        </tr>

                    </table>
                </div>
            </div>
                            <div class="text-area-btn">
                                <%= f.submit :新規登録, class: "btn btn-primary" %>
                            </div>



    <% end %>

</div>

app/views/admins/items/show.html.erb
<div class="container">
  <div class="row">
      <div class="mb-2 offset-md-1">
         <h3 class="admins-items-title">商品詳細</h3>
      </div>
  </div>


    <div class="items-form-area">
        <div class="image-area">
            <div class="">
              <%= attachment_image_tag @item, :image, size: '100x100', fallback: 'no_image_square.jpg', size: '200x200' %>
            </div>
        </div>

        <div class="text-area">
            <table>
                <tr>
                    <th class="">商品名</th>
                    <td><%= @item.name %></td>
                </tr>

                <tr>
                    <th class="">商品説明</th>
                    <td><%= @item.introduction %></td>
                </tr>

                <tr>
                    <th class="">ジャンル</th>
                    <td><%= @item.genre.name %></td>
                </tr>

                <tr>
                    <th class="">税込価格（税抜き価格）</th>
                    <td><%= @item_including_tax.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</td>
                </tr>

                <tr>
                    <th class="">販売ステータス</th>
                    <td><%= @item.is_active %></td>
                </tr>
            </table>
        </div>
    </div>

    <div class="text-area-btn">
        <%= link_to "編集する", edit_admins_item_path, class: "btn btn-primary text-white" %>
    </div>

</div>