config/routes.rb
Rails.application.routes.draw do

  root 'customers/homes#top'

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    get 'homes/top'
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  namespace :customers do
    get 'homes/about'
    post 'orders/confirm'
    get 'orders/complete'
    resources :orders, only:[:new, :create, :index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :items, only:[:index, :show]
    get 'customers/my_page/:id' => 'customers#show', as: 'my_page'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
    resources :customers, only:[:edit, :update]
    delete 'cart_items/destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :create]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item

    validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :encrypted_password, presence: true,
                                 length: { minimum:8 }

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  #  order/newで使う値を定義
   def full_name
    self.last_name + ' '+ self.first_name
   end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_paramas)
      redirect_to admins_customer_path(@customer.id)
    else
      render "edit"
    end
  end

  private

  def customer_paramas
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController
  before_action :authenticate_customer!
  before_action :hoge, if: proc { current_customer.is_deleted == true }

  def hoge
    sign_out
    redirect_to new_customer_registration_path
  end
  
  def index
    @address = Address.new
    @address.customer_id = current_customer.id
    @addresses = current_customer.addresses
  end

  def edit
    @address = Address.find(params[:id])
    @address.postal_code.tr!('０-９', '0-9')
  end

  def create
    @address = current_customer.addresses.new(address_params)
    # 全角数値=>半角数値に変換
    @address.postal_code.tr!('０-９', '0-9')
    @addresses = current_customer.addresses
    if @address.save
      redirect_to customers_addresses_path, notice: "配送先が登録されました"
    else
      render :index
    end
  end

  def update
    @address = Address.find(params[:id])
    # @address.postal_code.tr!('０-９', '0-9')がうまく機能しないため、各ビューで表示を工夫する。
    if @address.update(address_params)
      redirect_to customers_addresses_path, notice: "配送先が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to customers_addresses_path
  end


  protected
  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  before_action :authenticate_customer!
  before_action :hoge, if: proc { current_customer.is_deleted == true }

  def hoge
    sign_out
    redirect_to new_customer_registration_path
  end

  def index
    @cart_items = current_customer.cart_items
  end

  def update
    @cart_item = CartItem.find(params[:id])
    if @cart_item.update(cart_item_params)
      redirect_to customers_cart_items_path, notice: "個数が変更されました"
    else
      @cart_items = current_customer.cart_items
      render :index
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to customers_cart_items_path
  end

  def destroy_all
    @cart_items = current_customer.cart_items
    if @cart_items.count == 0
      render :index
    else
      @cart_items.destroy_all
      redirect_to customers_items_path
    end
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_items = current_customer.cart_items
    if @cart_item.save
      redirect_to customers_cart_items_path
    else
      render :index
    end
  end

  protected
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :customer_id, :amount)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  before_action :authenticate_customer!
  before_action :hoge, if: proc { current_customer.is_deleted == true }

  def hoge
    sign_out
    redirect_to new_customer_registration_path
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
    @customer.postal_code.tr!('０-９', '0-9')
    @customer.telephone_number.tr!('０-９', '0-9')
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "編集内容を保存しました！"
      redirect_to customers_my_page_path(@customer)
    else
      render :edit
    end
  end

  def unsubscribe
    @customer = current_customer
  end

  def withdraw
    @customer = current_customer
    # boolean型カラムis_deletedのステータスをfaulseからtrueに変更
    @customer.is_deleted = true
    # ユーザーのサインアウト(sign_out関数)
    sign_out
    redirect_to root_path
  end

  private
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number)
    end

end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController

  def top
    @genres = Genre.all
    @items = Item.last(4)

    # オススメ商品を指定したい時
    # @discography = Discography.select('name', 'artist')
    # @discography = Discography.select(:name, :artist)
  end

  def about
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  def index
    @genres = Genre.all
    # 以下ジャンル検索実装の記述箇所
    i = @genres.count #範囲オブジェクトの上限値として使うためにジャンルの個数をiと定義
    n = params[:order_sort].to_i # order_sortで受け取ったパラメータの値を整数型で取得しnと定義する
    case n
    when 1..i #order_sortが1~iの時
      @genre_name = Genre.find(n).name #ジャンルのn番目の主キーのnameカラムを取り出している
      @item_count = Item.where(genre_id: n) #genre_id: 1のカラムを持つ商品全てを配列で取得
      @items_paginate = @item_count.page(params[:page]).per(8) #whereで取り出したデータにページネーションを適用
    else #order_sortがnilの時
      @genre_name = "商品"
      @item_count = Item.all
      @items_paginate = Item.page(params[:page]).per(8)
    end
  end

  def show
    @genres = Genre.all
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :hoge, if: proc { current_customer.is_deleted == true }

  def hoge
    sign_out
    redirect_to new_customer_registration_path
  end

  def new
    @order = Order.new
    @addresses = current_customer.addresses
  end

  def confirm
    # Orderの受け皿を作る
    @order = Order.new(order_params)
    @order.shipping_cost = 800
    # CartItemからカート商品を取得
    @cart_items = current_customer.cart_items
    # ciの税込価格を計算、ciの合計金額を計算
    @sum = 0
    @cart_items.each do |ci|
      ci_tax_price = (ci.item.price * 1.1 * ci.amount).floor
      @sum += ci_tax_price
    end
    # orderの請求金額を計算
    @order.total_payment = @sum + @order.shipping_cost
    # orderのユーザー入力部分登録（@order.paymentはストロングパラメータorder_paramsで受け取り済）
    unless (@order.payment_method == 'クレジットカード') || (@order.payment_method == '銀行振込' )
      render :new
      return
    end
    # 選択した配送先の値を設定
    to_address = params[:to_address]
    if to_address == "0"
      @order.postal_code = current_customer.postal_code
      @order.address     = current_customer.address
      @order.name        = current_customer.full_name
      render :confirm
    elsif to_address == "1"
      @address = Address.find(params[:name][:id])
      @order.postal_code = @address.postal_code
      @order.address     = @address.address
      @order.name        = @address.name
      render :confirm
    elsif to_address == "2"
      # 新規の配送先を登録する
      @address = current_customer.addresses.new(address_params)
      @address.postal_code.tr!('０-９', '0-9')
      @address.save
      # 作成した新規配送先を基に、@orderのカラムを埋める
      @order.postal_code = @address.postal_code
      @order.address     = @address.address
      @order.name        = @address.name
      render :confirm
    else
      render :new
    end
    # POSTメソッドなのでrenderしてビューを取得する必要がある
    # fields_for 複数データを一度に保存する時に使用可能
  end

  def complete
  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    # CartItemからカート商品を取得
    cart_items = current_customer.cart_items
    if @order.save
      # カート商品から注文商品を作成、orderの合計金額を計算
      sum = 0
      cart_items.each do |ci|
        order_detail = OrderDetail.new(order_id: @order.id)
        order_detail.item_id = ci.item_id
        order_detail.price = (ci.item.price * 1.1).floor
        order_detail.amount = ci.amount
        order_detail.save
        # ここでカートitemを順次削除してもよい
        sum += order_detail.price
      end
      current_customer.cart_items.destroy_all
      redirect_to customers_orders_complete_path
    else
      render :confirm
    end
  end

  def index
    @orders = Order.where(customer_id: current_customer.id)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)
  end

  protected
  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :shipping_cost, :total_payment)
  end

  def order_detail_params
    params.require(:order_detail).permit(:order_id, :item_id, :price, :amount)
  end

  def customer_params
    params.require(:customer).permit(:last_name, :first_name)
  end

  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/views/customers/cart_items/index.html.erb
    <div class="row ml-0 mr-0">
        <div class="col-lg-8 title">
            <span class="bg-origin">ショッピングカート</h1>
        </div>
    <!--カートに商品がある時の表示画面-->
    <% if @cart_items.count > 0 %>
        <div class="col-lg-3 pt-4">
            <%= link_to customers_cart_items_destroy_all_path, method: :delete do %>
                <button type="button" class="btn btn-danger">カートを空にする</button>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 ml-3 mb-1">
            <%=  notice %>
        </div>
    </div>
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-bordered table-sm">
                    <thead>
                        <tr class="table-active">
                            <th class="align-middle">商品名</th>
                            <th class="align-middle">単価（税込）</th>
                            <th class="align-middle">数量</th>
                            <th class="align-middle">小計</th>
                            <th colspan="1"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @sum = 0 %>
                        <% @cart_items.each do |cart_item| %>
                            <tr>
                                <td class="align-middle">
                                    <%= attachment_image_tag cart_item.item, :image, format: 'jpeg', fallback: "no_image.jpg", size: "80x50" %>
                                    <%= cart_item.item.name %>
                                </td>
                                <td class="align-middle"><%= (cart_item.item.price * 1.1).floor.to_s(:delimited) %></td>
                                <td class="align-middle">
                                    <!--入力フォーム-->
                                    <%= form_with model: cart_item, url: customers_cart_item_path(cart_item.id), local: true do |f| %>
                                        <%= f.number_field :amount %>
                                        <%= f.submit "変更", class: "btn-sm btn-primary" %>
                                    <% end %>
                                </td>
                                <td class="align-middle">
                                    <% @each_sum = (cart_item.item.price * 1.1 * cart_item.amount).floor %>
                                    <%= (cart_item.item.price * 1.1 * cart_item.amount).floor.to_s(:delimited) %>
                                    <% @sum += @each_sum %>
                                </td>
                                <td class="align-middle text-center">
                                    <%= link_to customers_cart_item_path(cart_item.id), method: :delete do %>
            			                <button type="button" class="btn btn-danger", data: {confirm: "本当に削除しますか？"}>削除する</button>
            			            <% end %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-8">
                <%= link_to root_path do %>
                    <button type="button" class="btn btn-primary">買い物を続ける</button>
                <% end %>
            </div>
            <div class="col-lg-4">
                <table class="table table-bordered">
                    <tr>
                        <td class="table-active align-middle">合計金額</td>
                        <td class="align-middle"><%= @sum.floor.to_s(:delimited) %></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row justify-content-center">
            <%= link_to new_customers_order_path do %>
                <button type="button" class="btn btn-success btn-lg text-center">情報入力に進む</button>
            <% end %>
        </div>

    <!--カートが空の時の表示画面-->
<% else %>
        <div class="col-lg-10 col-lg-offset-1 title">
            <p>カートに商品がありません</p>
        </div>
    </div>
    <div class="row mr-0 ml-0">
        <div class="col-lg-8 ml-4">
            <%= link_to root_path do %>
                <button type="button" class="btn btn-primary">買い物を続ける</button>
            <% end %>
        </div>
    </div>
<% end %>